### ISSUE TITLE
Can I request an icon for gitlab?

### ISSUE THREAD

**Issue by jessemcallisterperry** [lykmapipo/themify-icons#7]
Hi there, 

Is it possible to request an icon for gitlab? I have a template I am using that uses your plugin for icons, but it only has github. I attempted to add a PR. This comes from https://simpleicons.org/icons/gitlab.svg.

[gitlab.svg.zip](https://github.com/lykmapipo/themify-icons/files/6371282/gitlab.svg.zip)

**Comment by lykmapipo** [comment]
@jptechnical We currently use icons from [themify.me](http://themify.me/themify-icons). Am not sure on possibility to mix with icons from [simpleicons.org]( https://simpleicons.org/icons).

**Quick:** You may also install simpleline icons as a package and use it. Its what I have been doing.

**Comment by jessemcallisterperry** [comment]
Thanks for responding. I mistakenly made this issue here, I meant to make it on the themify.me icons project. I had too many tabs open. 🥺

Please disregard.
